# Generated by Django 3.1 on 2021-10-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_grl', models.CharField(choices=[('Existencias', 'Existencias'), ('Lotes', 'Lotes')], default='Existencias', max_length=15, verbose_name='Tipo de Informe')),
                ('exist', models.PositiveIntegerField(default=0, verbose_name='Existencias')),
            ],
            options={
                'verbose_name': 'Informe General',
                'verbose_name_plural': 'Informes Generales',
                'db_table': 'informe_general',
            },
        ),
    ]
